### ISSUE TITLE
down不来

### ISSUE THREAD

**Issue by yrickwong** [nichbar/r2generator#2]
Unable to find method 'com.android.build.gradle.tasks.ProcessAndroidResources.getOriginalApplicationId()Ljava/lang/String;'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by nichbar** [comment]
Sorry for the late response.

Base on the stack trace that you pasted above, you may need a proxy to download gradle.

**Comment by yrickwong** [comment]
找到问题了 哥们，我用的gradle是3.3的  你这个环境是3.0的  语法改了

**Comment by nichbar** [comment]
Pull requests are always welcome :)

**Comment by nichbar** [comment]
Fix this in commit https://github.com/nichbar/r2generator/commit/d89f5e514d890d576bc12a2f80c2c84d63555050
